# Generated by Django 4.2 on 2023-04-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_rename_subcategory_categories_parent"),
        ("menu", "0002_alter_menuitem_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("categories", models.ManyToManyField(to="blog.categories")),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
