# Generated by Django 4.2 on 2023-04-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_categories_options_alter_posts_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories",
            name="parent",
        ),
        migrations.AddField(
            model_name="categories",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_category",
                to="blog.categories",
            ),
        ),
    ]
