# Generated by Django 4.2 on 2023-04-18 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_categories_parent_categories_subcategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categories",
            old_name="subcategory",
            new_name="parent",
        ),
    ]
